# Generated by Django 5.2.8 on 2025-11-09 20:18

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'verbose_name': 'Ответ на вопрос', 'verbose_name_plural': 'Ответы на вопросы'},
        ),
        migrations.AlterModelOptions(
            name='answerreaction',
            options={'verbose_name': 'Лайк к ответу', 'verbose_name_plural': 'Лайки к ответу'},
        ),
        migrations.AlterModelOptions(
            name='question',
            options={'verbose_name': 'Вопрос', 'verbose_name_plural': 'Вопросы'},
        ),
        migrations.AlterModelOptions(
            name='questionreaction',
            options={'verbose_name': 'Лайк к вопросу', 'verbose_name_plural': 'Лайки к вопросу'},
        ),
        migrations.AlterModelOptions(
            name='userprofile',
            options={'verbose_name': 'Профиль пользователя', 'verbose_name_plural': 'Профили пользователя'},
        ),
        migrations.AlterUniqueTogether(
            name='answerreaction',
            unique_together={('answer', 'author')},
        ),
        migrations.AlterUniqueTogether(
            name='questionreaction',
            unique_together={('question', 'author')},
        ),
    ]
