# Generated by Django 5.2.8 on 2025-11-10 13:04

import django.db.models.manager
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0002_alter_answer_options_alter_answerreaction_options_and_more'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='answer',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='question',
            managers=[
                ('active', django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='answerreaction',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='questionreaction',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='answer',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Видно ли пользователям?', verbose_name='Активно ли?'),
        ),
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Видно ли пользователям?', verbose_name='Активно ли?'),
        ),
    ]
