# Generated by Django 5.2.8 on 2025-11-10 13:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0004_tag_question_tag'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='tag',
            new_name='tags',
        ),
    ]
