# Generated by Django 5.2.8 on 2025-11-10 13:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0005_rename_tag_question_tags'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='autor',
            new_name='author',
        ),
    ]
