# Generated by Django 5.2.8 on 2025-11-10 21:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('questions', '0006_rename_autor_question_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='dislikes_count',
            field=models.IntegerField(default=0, verbose_name='Количество дизлайков'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name='Количество лайков'),
        ),
        migrations.AlterField(
            model_name='answerreaction',
            name='answer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.answer', verbose_name='Родительский ответ'),
        ),
        migrations.AlterField(
            model_name='question',
            name='dislikes_count',
            field=models.IntegerField(default=0, verbose_name='Количество дизлайков'),
        ),
        migrations.AlterField(
            model_name='question',
            name='likes_count',
            field=models.IntegerField(default=0, verbose_name='Количество лайков'),
        ),
        migrations.AlterField(
            model_name='questionreaction',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='questions.question', verbose_name='Родительский вопрос'),
        ),
    ]
